Site Barbearia/Site Barbearia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site_Barbearia.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
      
    }
}

Site Barbearia/Site Barbearia/Controllers/ServiçosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site_Barbearia.Controllers
{
    public class ServiçosController : Controller
    {
        // GET: Serviços
        public ActionResult Index()
        {
            return View();
        }

        Business.BsServiços.BusinessServiços businessServiços = new Business.BsServiços.BusinessServiços();

        public ActionResult NovoAtendimento()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NovoAtendimento(Database.Entity.tb_servico model)
        {
            businessServiços.NovoAtendimento(model);

            return View();
        }

        public ActionResult ConsultarServiço()
        {
            List<Database.Entity.tb_servico> lista = businessServiços.ListarServiços();

            return View(lista);
        }

        /*[HttpPost]
        public ActionResult ConsultarServiço(Database.Entity.tb_servico model)
        {
            List<Database.Entity.tb_servico> lista = businessServiços.ListarServiços();

            return View(lista);
        }*/

        public ActionResult AlterarServiço()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AlterarServiço(Database.Entity.tb_servico model)
        {
            businessServiços.AlterarServiço(model);

            return View();
        }


        public ActionResult RemoverServiço()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RemoverServiço(Database.Entity.tb_servico model)
        {
            businessServiços.RemoverServiço(model);

            return View();
        }
    }
}

Site Barbearia/Site Barbearia/Controllers/UsuárioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site_Barbearia.Controllers
{
    public class UsuárioController : Controller
    {
        // GET: Usuário
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewCadastro()
        {
            return View();
        }

    }
}

Site Barbearia/Site Barbearia/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h4 style="font-size:30px">Nossa História</h4>

<p>
    A idéia de abrir um negócio foi de um dos sócios, mas não queria fazer isso sozinho então ela resolveu chamar os amigos, que assim como ela tinha experiência.
    Combinaram de se encontrar para discutir sobre o assunto, todos deram idéias e depois de muito tempo discutindo chegaram a um acordo.
    No primeiro momento a intenção era fazer um salão feminino, mas já é algo comum então apenas mudamos o público alvo para o masculino que hoje em dia os homens estão se cuidando mais e procurando um lugar para sua transformação.
    Com essa decisão criaram uma barbearia com 3 barbeiros, 1 Aux de limpeza, 1 recepcionista, 1 Balconista de bar e 1 gerente. O nome The Barber's House foi escolhido para que todos se sintam em casa e confortáveis.
</p>

<br />
<h5 style="font-size:25px">Missão</h5>

<br />
<p>A missão da nossa empresa é oferecer a melhor qualidade de atendimento possível, com diversão e petiscos ou bebidas para nossos clientes.</p>
<br />
<h6 style="font-size:25px">Visão</h6>

<br />
<p>A visão da nossa empresa é expandir para todo o país, sendo reconhecidos mundialmente  por termos um ótimo trabalho.</p>
<br />

<h7 style="font-size:25px">Valores</h7>
<br />
<br />
<p>- buscar constantemente a satisfação de nossos clientes;</p>
<p>- ter respeito ao ambiente;</p>
<p>- Responsabilidade é ética;</p>
<p>- Respeitar a todos;</p>
<p>- Sempre fazer as coisas pensando no crescimento da empresa;</p>
<p>- Sempre seguir a regra "O cliente tem sempre razão";</p>
<p>- Dar ao cliente  toda atenção que ele precisa.</p>

Site Barbearia/Site Barbearia/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<br />
<address align="left">
    <p style="font-size:20px">Para qualquer dúvida?</p>
    <strong>Email:</strong><br /><p>TheBarber`sHouse@gmail.com</p><br />
</address>

<address align="left" style="font-size:20px">
    Rua Wisord - Vila Mariana N°33<br />
    São Paulo, SP<br />

</address>

Site Barbearia/Site Barbearia/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pagína Inicial";
}

<div class="body-content">
<div class="jumbotron">
    <h1 style="font-size:35px">Bem-Vindo a The Barber´s House</h1>
</div>

<div class="jumbotron" align="left">
    <h1 style="font-size:30px">Cortes</h1>
    <br />
    <br />
    <h1 style="font-size: 20px">Cortes em Geral - R$50,00</h1>
    <br />
    <h2 style="font-size: 20px">Cortes Infantis	- R$ 35,00</h2>
    <br />
    <h3 style="font-size: 20px">Barba	- R$45,00 	</h3>
    <br />
    <h4 style="font-size: 20px">Pezinho	- R$25,00 </h4>
</div>

<div class="jumbotron" align="left">
    <h1 style="font-size:30px">Outros procedimentos</h1>
    <br />
    <br />
    <h1 style="font-size: 20px">Relaxamento	- R$ 25,00 	</h1>
    <br />
    <h2 style="font-size: 20px">Limpeza de Sombrancelha - R$20,00 </h2>
    <br />
    <h3 style="font-size: 20px">Progressiva	- R$ 50,00 </h3>
    <br />
    <h4 style="font-size: 20px">Escova - R$ 25,00</h4>
</div>

<div class="jumbotron" align="left">
    <h1 style="font-size:30px"> Combos</h1>
    <br />
    <br />
    <h1 style="font-size: 20px">Combo (Barba+Cabelo) - R$ 90,00</h1>
    <br />
    <h2 style="font-size: 20px">Combo (Barba+Cabelo+Progressiva)- R$ 140,00</h2>
</div>
</div>

Site Barbearia/Site Barbearia/Views/Serviços/AlterarServiço.cshtml
@model Site_Barbearia.Database.Entity.tb_servico

@{
    ViewBag.Title = "AlterarServiço";
}

<h2>AlterarServiço</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tb_servico</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_servico)

        <div class="form-group">
            @Html.LabelFor(model => model.nm_responsavel_servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nm_responsavel_servico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nm_responsavel_servico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dt_servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dt_servico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dt_servico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vl_servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vl_servico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vl_servico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hr_servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hr_servico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hr_servico, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "ConsultarServiço","Serviços")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Site Barbearia/Site Barbearia/Views/Serviços/ConsultarServiço.cshtml
@model IEnumerable<Site_Barbearia.Database.Entity.tb_servico>

@{
    ViewBag.Title = "Consultar Serviço";
}

<h2>ConsultarServiço</h2>

<p>
    @Html.ActionLink("Criar Novo", "NovoAtendimento")
</p>
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.dt_servico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vl_servico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hr_servico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tb_cliente.nm_cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tb_corte.nm_corte)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.dt_servico.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vl_servico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hr_servico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tb_cliente.nm_cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tb_corte.nm_corte)
            </td>

            <td>
                @Html.ActionLink("Alterar Serviço", "AlterarServiço", new { id = item.id_servico }) |
                @Html.ActionLink("Remover Serviço", "RemoverServiço", new { id = item.id_servico })
            </td>
        </tr>
    }

</table>

Site Barbearia/Site Barbearia/Views/Serviços/NovoAtendimento.cshtml
@model Site_Barbearia.Database.Entity.tb_servico

@{
    ViewBag.Title = "Novo Atendimento";
}

<h2>NovoAtendimento</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.tb_cliente.nm_cliente, "Seu Nome:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tb_cliente.nm_cliente, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tb_cliente.nm_cliente, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.dt_servico, "Data desejada:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dt_servico, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dt_servico, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.vl_servico, "Serviço:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select id=Valor style="font-size: 17px">
                <option>Selecione o corte</option>
                <option>Relaxamento	- R$ 25,00</option>
                <option>Limpeza de Sombrancelha - R$20,00</option>
                <option>Cortes em Geral - R$50,00</option>
                <option>Cortes Infantis	- R$ 35,00</option>
                <option>Barba - R$45,00 </option>
                <option>Pezinho	- R$25,00 </option>
                <option>Progressiva	- R$ 50,00</option>
                <option>Escova	- R$ 25,00</option>
                <option>Combo (Barba+Cabelo)- R$ 90,00</option>
                <option>(Barba+Cabelo+Progressiva)- R$ 140,00</option>
            </select>
        </div>
        @Html.ValidationMessageFor(model => model.vl_servico, "", new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.hr_servico,"Hora desejada", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.hr_servico, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.hr_servico, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cadastrar Serviço" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Ir para lista","ConsultarServiço", "Serviços")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Site Barbearia/Site Barbearia/Views/Serviços/RemoverServiço.cshtml
@model Site_Barbearia.Database.Entity.tb_servico

@{
    ViewBag.Title = "RemoverServiço";
}

<h2>RemoverServiço</h2>

<h3>Tem certeza que quer remover esse serviço?</h3>
<div>
    <h4>tb_servico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nm_responsavel_servico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nm_responsavel_servico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_servico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_servico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vl_servico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vl_servico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hr_servico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hr_servico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_cliente.nm_cliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_cliente.nm_cliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_corte.nm_corte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_corte.nm_corte)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar a lista", "ConsultarServiço","Serviços")
        </div>
    }
</div>

Site Barbearia/Site Barbearia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TheBarber`s House </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Barber`s House", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Serviços", "NovoAtendimento", "Serviços")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The Barber´s House </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Site Barbearia/Site Barbearia/Views/Usuário/ViewCadastro.cshtml
@model Site_Barbearia.Database.Entity.tb_usuario

@{
    ViewBag.Title = "ViewCadastro";
}

<h2>Cadastro</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nm_usuario,"Usuário:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nm_usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nm_usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nm_senha,"Senha:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nm_senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nm_senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}